
CREATE TABLE users (

    id NUMBER GENERATEd BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR2(255) NOT NULL,
    username VARCHAR2(255) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(255) DEFAULT 'user' NOT NULL CHECK (role IN ('user', 'instructor', 'admin')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE courses(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_title VARCHAR2(255) UNIQUE NOT NULL,
    course_description CLOB,
    thumbnail VARCHAR2(255),
    category VARCHAR2(255),
    price NUMBER NOT NULL,
    slug VARCHAR2(255) UNIQUE NOT NULL,
    difficulty_level VARCHAR2(255) NOT NULL CHECK (difficulty_level IN ('beginner', 'intermediate', 'advanced')),
    duration NUMBER,
    status VARCHAR2(255) DEFAULT 'published' CHECK (status IN ('draft', 'published', 'archived')),
    enrollment_count NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

DROP TABLE courses;

SELECT * FROM users;
SELECT * FROM courses;